### ISSUE TITLE
Issue with hashfile

### ISSUE THREAD

**Issue by leandrogomesmachado** [MatthewLM/PeercoinAbeExplorer#1]
hello, I install all the items needed to configure this Instance but I have this problem:
![screenshot_2](https://cloud.githubusercontent.com/assets/3827247/6271619/f77dc376-b848-11e4-9253-c67b33e6de19.jpg)

I am trying to install an instance of abe for x15 coin, with another coin I installed all and are ok (just an RPC problem) but in this script I have this problems and can't fix on initial load.

Thanks

**Comment by MatthewLM** [comment]
Hi, you need to add a path to a hashfile in your config like this:

```
hashfile = /home/abe/hashfile.dat
```

This file need to exist so touch it:

```
$ touch /home/abe/hashfile.dat
```
