### ISSUE TITLE
Raw genesis TX

### ISSUE THREAD

**Issue by Bushstar** [MatthewLM/PeercoinAbeExplorer#2]
Quick question I hope. How did you get the genesis raw transaction data for ABE as shown here?

https://github.com/MatthewLM/PeercoinAbeExplorer/commit/0d09d545fe0dc79393bd4e41e297b6b60069269f

**Comment by MatthewLM** [comment]
Hi, I used the xxd command on the blk0001.dat file to determine the hex value of the genesis transaction. Using some knowledge of the block format I could extract the particular data required.

**Comment by Bushstar** [comment]
Thanks for the response. Got it with a hex editor. Could not find this documented anywhere but it is simple enough.
